(global-set-key [f12] 'sr-speedbar-toggle)
(global-set-key [f8] 'neotree-toggle)
(global-set-key [f9] 'color-theme-gnome2)
(define-key global-map [C-return] 'set-mark-command)
(global-set-key "%" 'match-paren)
